version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tset
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=brodvovan@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres

    ports:
      - '8001:80'
volumes:
  db:
    driver: local